---
config:
      theme: redux
---
flowchart TD
    subgraph hadoop[Hadoop]
        hdfs(HDFS)
        hbase(HBase)
        spark(Spark Streaming)
        java(Custom JAR)
    end

    subgraph gcp[Google Cloud Platform]
        gcs(Google Cloud Storage)
        bigtable(Cloud Bigtable)
    end

    hdfs --- java
    java --- gcs
    hbase --- spark
    spark --- bigtable
